var searchData=
[
  ['c3_5fassimilation_0',['c3_assimilation',['../classstandard_b_m_l_1_1c3__assimilation.html#a5a0dff890013571b995ee3cc09d03f9e',1,'standardBML::c3_assimilation']]],
  ['c3_5fcanopy_1',['c3_canopy',['../classstandard_b_m_l_1_1c3__canopy.html#af90d78d048115ea86b02a3d2183756d8',1,'standardBML::c3_canopy']]],
  ['c3_5fleaf_5fphotosynthesis_2',['c3_leaf_photosynthesis',['../classstandard_b_m_l_1_1c3__leaf__photosynthesis.html#ae71f3cdfe179f53d0ea5785475d10dca',1,'standardBML::c3_leaf_photosynthesis']]],
  ['c3canac_3',['c3CanAC',['../c3_can_a_c_8h.html#acf1e43c1775aa338c7da17a75cce4bdc',1,'c3CanAC(double LAI, double cosine_zenith_angle, double solarR, double air_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight, double beta_PSII):&#160;c3CanAC.cpp'],['../c3_can_a_c_8cpp.html#acf1e43c1775aa338c7da17a75cce4bdc',1,'c3CanAC(double LAI, double cosine_zenith_angle, double solarR, double air_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight, double beta_PSII):&#160;c3CanAC.cpp']]],
  ['c3evapotrans_4',['c3EvapoTrans',['../c3_evapo_trans_8cpp.html#a61b7d88adafff31f703008da477eb090',1,'c3EvapoTrans(double absorbed_shortwave_radiation, double air_temperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomatal_conductance, double minimum_gbw, double WindSpeedHeight):&#160;c3EvapoTrans.cpp'],['../_bio_cro_8h.html#a61b7d88adafff31f703008da477eb090',1,'c3EvapoTrans(double absorbed_shortwave_radiation, double air_temperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomatal_conductance, double minimum_gbw, double WindSpeedHeight):&#160;c3EvapoTrans.cpp']]],
  ['c3photoc_5',['c3photoC',['../c3photo_8cpp.html#a6fb9a0b8b2ba6b11797a40e8b42bdb07',1,'c3photoC(double const absorbed_ppfd, double const Tleaf, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const bb0, double const bb1, double const Gs_min, double Ca, double const AP, double const O2, double const thet, double const StomWS, int const water_stress_approach, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII):&#160;c3photo.cpp'],['../c3photo_8hpp.html#a6fb9a0b8b2ba6b11797a40e8b42bdb07',1,'c3photoC(double const absorbed_ppfd, double const Tleaf, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const bb0, double const bb1, double const Gs_min, double Ca, double const AP, double const O2, double const thet, double const StomWS, int const water_stress_approach, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII):&#160;c3photo.cpp']]],
  ['c4_5fassimilation_6',['c4_assimilation',['../classstandard_b_m_l_1_1c4__assimilation.html#adc6d82ea8fdc264efdb6ea20f943738c',1,'standardBML::c4_assimilation']]],
  ['c4_5fcanopy_7',['c4_canopy',['../classstandard_b_m_l_1_1c4__canopy.html#a94d23dfe2a067f56b731d38f379f2d9c',1,'standardBML::c4_canopy']]],
  ['c4_5fleaf_5fphotosynthesis_8',['c4_leaf_photosynthesis',['../classstandard_b_m_l_1_1c4__leaf__photosynthesis.html#ab4a252ecfb25a713e36d6af419915e79',1,'standardBML::c4_leaf_photosynthesis']]],
  ['c4photoc_9',['c4photoC',['../c4photo_8cpp.html#a2613ca2f3d1f34c768aacfbd0de1dd3e',1,'c4photoC(double Qp, double leaf_temperature, double relative_humidity, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT):&#160;c4photo.cpp'],['../c4photo_8h.html#a21ffc36b1b0fa5d152ca787d71d9283b',1,'c4photoC(double Qp, double Tl, double RH, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT):&#160;c4photo.cpp']]],
  ['canac_10',['CanAC',['../_can_a_c_8cpp.html#a6fa729b5ad5a8d83d7f724b942403d13',1,'CanAC(double LAI, double cosine_zenith_angle, double solarR, double temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const struct nitroParms &amp;nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw):&#160;CanAC.cpp'],['../_can_a_c_8h.html#a6fa729b5ad5a8d83d7f724b942403d13',1,'CanAC(double LAI, double cosine_zenith_angle, double solarR, double temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const struct nitroParms &amp;nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw):&#160;CanAC.cpp']]],
  ['collatz_5fphoto_11',['collatz_photo',['../collatz__photo_8cpp.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp'],['../collatz__photo_8hpp.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp']]],
  ['compute_5fwsphoto_12',['compute_wsPhoto',['../_aux_bio_cro_8cpp.html#a058be0e6ed718b377d7c6056cceb09a8',1,'AuxBioCro.cpp']]]
];
