The BioCro C++ Library: se_module Namespace Reference
se_module Namespace Reference
Classes
class base
A general module that solves a set of simultaneous equations. Note that this module cannot be created by the module_factory since its constructor has a different signature than a typical module. Instead, it must have concrete derived classes. This class has been made abstract to indicate this.
Functions
std::string get_ncalls_output_name (std::string const &module_name)
Returns the name of an output quantity that describes the number of times the simultaneous equations were evaluated while solving for the unknowns.
std::string get_nsteps_output_name (std::string const &module_name)
Returns the name of an output quantity that describes the number of steps the solver took.
std::string get_success_output_name (std::string const &module_name)
Returns the name of an output quantity that indicates whether the solver was successful in finding a solution.
string_vector get_se_inputs (mc_vector mcs)
Returns a sorted list of inputs required by the modules, excluding any unknown quantities.
string_vector get_se_outputs (mc_vector mcs)
Returns a sorted list of outputs produced by the modules.
std::unique_ptr< simultaneous_equations > make_se (mc_vector mcs)
Make a simultaneous_equations object from the modules.
std::vector< std::vector< double > > reorder_initial_guesses (std::vector< std::vector< double > > initial_guesses, std::unique_ptr< simultaneous_equations > const &se)
Reorders the initial guesses according to their corresponding f_scalar_norm values.
Function Documentation
get_ncalls_output_name()
std::string get_ncalls_output_name (std::string const & module_name)
Returns the name of an output quantity that describes the number of times the simultaneous equations were evaluated while solving for the unknowns.
Definition at line 22 of file se_module.h.
get_nsteps_output_name()
std::string get_nsteps_output_name (std::string const & module_name)
Returns the name of an output quantity that describes the number of steps the solver took.
Definition at line 31 of file se_module.h.
get_se_inputs()
string_vector get_se_inputs (mc_vector mcs)
Returns a sorted list of inputs required by the modules, excluding any unknown quantities.
Definition at line 48 of file se_module.h.
References find_strictly_required_inputs(), get_unknown_quantities(), string_set_to_string_vector(), and string_vector_difference().
Referenced by make_se().
get_se_outputs()
string_vector get_se_outputs (mc_vector mcs)
Returns a sorted list of outputs produced by the modules.
Definition at line 66 of file se_module.h.
References find_unique_module_outputs(), and string_set_to_string_vector().
get_success_output_name()
std::string get_success_output_name (std::string const & module_name)
Returns the name of an output quantity that indicates whether the solver was successful in finding a solution.
Definition at line 40 of file se_module.h.
make_se()
std::unique_ptr< simultaneous_equations > make_se (mc_vector mcs)
Make a simultaneous_equations object from the modules.
Definition at line 74 of file se_module.h.
References get_se_inputs(), and get_unknown_quantities().
reorder_initial_guesses()
std::vector< std::vector< double > > reorder_initial_guesses (std::vector< std::vector< double > > initial_guesses, std::unique_ptr< simultaneous_equations > const & se)
Reorders the initial guesses according to their corresponding f_scalar_norm values.
Definition at line 94 of file se_module.h.
References f_scalar_norm_from_f_vec(), and se_module_print.
Referenced by base::do_operation().