The BioCro C++ Library: /github/workspace/src/module_library/CanAC.cpp File Reference
CanAC.cpp File Reference
#include "BioCro.h"
#include "c4photo.h"
#include "../framework/constants.h"
Functions
struct Can_Str CanAC (double LAI, double cosine_zenith_angle, double solarR, double temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const struct nitroParms &nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw)
Function Documentation
CanAC()
struct Can_Str CanAC (double LAI, double cosine_zenith_angle, double solarR, double temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const struct nitroParms & nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw)
Definition at line 5 of file CanAC.cpp.
References Can_Str::Assim, c4_str::Assim, Light_profile::average_absorbed_shortwave, c4photoC(), Can_Str::canopy_conductance, Can_Str::canopy_transpiration_penman, Can_Str::canopy_transpiration_priestly, ET_Str::Deltat, Light_model::diffuse_irradiance_fraction, Light_model::direct_irradiance_fraction, ET_Str::EPenman, ET_Str::EPriestly, EvapoTrans2(), Can_Str::GrossAssim, c4_str::GrossAssim, c4_str::Gs, lightME(), LNprof(), RHprof(), Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, sunML(), Can_Str::Trans, ET_Str::TransR, and WINDprof().
Referenced by c4_canopy::do_operation().